### ISSUE TITLE
About Apollo-SouthBay

### ISSUE THREAD

**Issue by Huangzichen13** [HKUST-Aerial-Robotics/LiDAR-Registration-Benchmark#1]
Can you publish the Apollo-SouthBay dataset containing source point cloud, target point cloud, and GT?

**Comment by qiaozhijian** [comment]
Hello,
Datasets can be downloaded here:
https://developer.apollo.auto/southbay.html
GT can be found here:
https://github.com/HKUST-Aerial-Robotics/LiDAR-Registration-Benchmark/tree/main/benchmarks/apollo_lc
